/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Creates a barrel-file
 */
// eslint-disable-next-line @typescript-eslint/naming-convention
export interface Barrel {
    /**
     * The path at which to create the component file, relative to the current workspace. Default is a folder with the same name as the component in the project root.
     */
    path: string;
    /**
     * Path of file to export
     */
    file?: string;
    /**
     * Custom export path to add to the barrel file
     */
    export?: string;
    /**
     * Name of the barrel file
     */
    name?: string;

    [k: string]: unknown;
}
