name: Publish to npmjs.org

on:
    release:
        types: [published, prereleased]

    workflow_dispatch:

jobs:
    publish:
        name: Publish to NPM
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Use Node.js
              uses: actions/setup-node@v3
              with:
                  node-version-file: '.nvmrc'
                  registry-url: 'https://registry.npmjs.org/'

            - name: Install dependencies
              run: npm ci

            - name: Build
              run: npx nx build composables

            - name: Publish
              working-directory: ./dist/libs/composables
              run: npm publish --access public
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
